//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:00:00 PM CEST 
//


package org.omg.spec.bpmn._20100524.model;



import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

import partes.refactorRunner.InteractionTreeBuilder;



/**
 * <p>Java class for tFlowNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tFlowNode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tFlowElement">
 *       &lt;sequence>
 *         &lt;element name="incoming" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tFlowNode", propOrder = {
    "incoming",
    "outgoing"
})
@XmlSeeAlso({
    TEvent.class,
    TChoreographyActivity.class,
    TGateway.class,
    TActivity.class
})
public abstract class TFlowNode
    extends TFlowElement
{

    protected List<QName> incoming;
    protected List<QName> outgoing;

    /**
     * Gets the value of the incoming property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incoming property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncoming().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QName }
     * 
     * 
     */
    public List<QName> getIncoming() {
        if (incoming == null) {
            incoming = new ArrayList<QName>();
        }
        return this.incoming;
    }

    /**
     * Gets the value of the outgoing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outgoing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutgoing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QName }
     * 
     * 
     */
    public List<QName> getOutgoing() {
        if (outgoing == null) {
            outgoing = new ArrayList<QName>();
        }
        return this.outgoing;
    }
    
   // public abstract void perform();
	
	public void doStep() {
	//	perform();
		
		this.setActionable(false);
		
		Iterator<QName> outgoingIterator = getOutgoing().iterator();	
		while(outgoingIterator.hasNext()){
			QName sfname = outgoingIterator.next();
	
			List<JAXBElement<? extends TRootElement>> content;
			try {
				content = InteractionTreeBuilder.getContent();
			
			TChoreography choreography = new TChoreography();	
			if (content.get(0).getValue() instanceof TChoreography){
				choreography = (TChoreography) content.get(0).getValue();	
			}
			Iterator<JAXBElement<? extends TFlowElement>> flowElements = choreography.getFlowElement().iterator();
			while(flowElements.hasNext()){
				TFlowElement fte = flowElements.next().getValue();
				
				if (fte.getId().equals(sfname.getLocalPart())){
					TSequenceFlow sf = (TSequenceFlow) fte;
					//System.out.println("settato actionable: " + sf.getId());
					sf.setActionable(true);
					//((TFlowElement) sf.getTargetRef()).setActionable(true);
				}
			}
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (JAXBException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		
	}

}
