/**
 *
 * Copyright (C) 2012  Midhat Ali, Andrea Polini, Guglielmo De Angelis
 *
 * This file is part of ServicePot ver 0.1 .
 *
 * ServicePot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ServicePot.  If not, see <http:www.gnu.org/licenses/>.
 */
package org.uddi.v3_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-02-02T15:14:55.202+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "urn:uddi-org:v3_service", name = "UDDI_Inquiry_PortType")
@XmlSeeAlso({org.uddi.custody_v3.ObjectFactory.class, org.uddi.api_v3.ObjectFactory.class, org.uddi.repl_v3.ObjectFactory.class, org.uddi.sub_v3.ObjectFactory.class, org.uddi.vs_v3.ObjectFactory.class, org.uddi.policy_v3.ObjectFactory.class, org.uddi.vscache_v3.ObjectFactory.class, org.uddi.policy_v3_instanceparms.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, org.uddi.subr_v3.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UDDIInquiryPortType {

    @WebResult(name = "bindingDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_bindingDetail", action = "get_bindingDetail")
    public org.uddi.api_v3.BindingDetail getBindingDetail(
        @WebParam(partName = "body", name = "get_bindingDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetBindingDetail body
    );

    @WebResult(name = "serviceList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_service", action = "find_service")
    public org.uddi.api_v3.ServiceList findService(
        @WebParam(partName = "body", name = "find_service", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindService body
    );

    @WebResult(name = "serviceDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_serviceDetail", action = "get_serviceDetail")
    public org.uddi.api_v3.ServiceDetail getServiceDetail(
        @WebParam(partName = "body", name = "get_serviceDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetServiceDetail body
    );

    @WebResult(name = "tModelDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_tModelDetail", action = "get_tModelDetail")
    public org.uddi.api_v3.TModelDetail getTModelDetail(
        @WebParam(partName = "body", name = "get_tModelDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetTModelDetail body
    );

    @WebResult(name = "bindingDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_binding", action = "find_binding")
    public org.uddi.api_v3.BindingDetail findBinding(
        @WebParam(partName = "body", name = "find_binding", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindBinding body
    );

    @WebResult(name = "businessList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_business", action = "find_business")
    public org.uddi.api_v3.BusinessList findBusiness(
        @WebParam(partName = "body", name = "find_business", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindBusiness body
    );

    @WebResult(name = "relatedBusinessesList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_relatedBusinesses", action = "find_relatedBusinesses")
    public org.uddi.api_v3.RelatedBusinessesList findRelatedBusinesses(
        @WebParam(partName = "body", name = "find_relatedBusinesses", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindRelatedBusinesses body
    );

    @WebResult(name = "businessDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_businessDetail", action = "get_businessDetail")
    public org.uddi.api_v3.BusinessDetail getBusinessDetail(
        @WebParam(partName = "body", name = "get_businessDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetBusinessDetail body
    );

    @WebResult(name = "tModelList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_tModel", action = "find_tModel")
    public org.uddi.api_v3.TModelList findTModel(
        @WebParam(partName = "body", name = "find_tModel", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindTModel body
    );

    @WebResult(name = "operationalInfos", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_operationalInfo", action = "get_operationalInfo")
    public org.uddi.api_v3.OperationalInfos getOperationalInfo(
        @WebParam(partName = "body", name = "get_operationalInfo", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetOperationalInfo body
    );
}
