
package partes.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PartesWsTestGenerator", targetNamespace = "http://service.partes", wsdlLocation = "http://127.0.0.1:8080/PartesWsTestGenerator/services/PartesWsTestGenerator?wsdl")
public class PartesWsTestGenerator
    extends Service
{

    private final static URL PARTESWSTESTGENERATOR_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(partes.service.PartesWsTestGenerator.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = partes.service.PartesWsTestGenerator.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/PartesWsTestGenerator/services/PartesWsTestGenerator?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/PartesWsTestGenerator/services/PartesWsTestGenerator?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PARTESWSTESTGENERATOR_WSDL_LOCATION = url;
    }

    public PartesWsTestGenerator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartesWsTestGenerator() {
        super(PARTESWSTESTGENERATOR_WSDL_LOCATION, new QName("http://service.partes", "PartesWsTestGenerator"));
    }

    /**
     * 
     * @return
     *     returns PartesWsTestGeneratorPortType
     */
    @WebEndpoint(name = "PartesWsTestGeneratorHttpSoap11Endpoint")
    public PartesWsTestGeneratorPortType getPartesWsTestGeneratorHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.partes", "PartesWsTestGeneratorHttpSoap11Endpoint"), PartesWsTestGeneratorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartesWsTestGeneratorPortType
     */
    @WebEndpoint(name = "PartesWsTestGeneratorHttpSoap11Endpoint")
    public PartesWsTestGeneratorPortType getPartesWsTestGeneratorHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.partes", "PartesWsTestGeneratorHttpSoap11Endpoint"), PartesWsTestGeneratorPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PartesWsTestGeneratorPortType
     */
    @WebEndpoint(name = "PartesWsTestGeneratorHttpSoap12Endpoint")
    public PartesWsTestGeneratorPortType getPartesWsTestGeneratorHttpSoap12Endpoint() {
        return super.getPort(new QName("http://service.partes", "PartesWsTestGeneratorHttpSoap12Endpoint"), PartesWsTestGeneratorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartesWsTestGeneratorPortType
     */
    @WebEndpoint(name = "PartesWsTestGeneratorHttpSoap12Endpoint")
    public PartesWsTestGeneratorPortType getPartesWsTestGeneratorHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.partes", "PartesWsTestGeneratorHttpSoap12Endpoint"), PartesWsTestGeneratorPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PartesWsTestGeneratorPortType
     */
    @WebEndpoint(name = "PartesWsTestGeneratorHttpEndpoint")
    public PartesWsTestGeneratorPortType getPartesWsTestGeneratorHttpEndpoint() {
        return super.getPort(new QName("http://service.partes", "PartesWsTestGeneratorHttpEndpoint"), PartesWsTestGeneratorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartesWsTestGeneratorPortType
     */
    @WebEndpoint(name = "PartesWsTestGeneratorHttpEndpoint")
    public PartesWsTestGeneratorPortType getPartesWsTestGeneratorHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.partes", "PartesWsTestGeneratorHttpEndpoint"), PartesWsTestGeneratorPortType.class, features);
    }

}
